#!bin/bash 


arg1=$1
arg2=$2

error(){	echo "This is error message"
		echo "Please Type help"
}
help(){		echo "This is help"
		echo "Install Apache = Apache ကို Install လုပ္လိမ့္မယ္ "
		echo "Install MySQL  = MySQL ကို Install လုပ္လိမ့္မယ္ "
}
	if [ $arg1 = Install ]
	then
		if [ $arg2 = Apache ]
	     	then
			echo " Apache "
			exit 
		elif [ $arg2 = MySQL ]
		then 
			echo " MySQL "
			exit
		else 	
			error
			exit
		fi
       elif [ $arg1 = help ] 
	then 
			help
	else 
		error 		
		fi 


