#!bin/bash 

arg1=$1
arg2=$2

while true
do
	if [ $arg1 = Install ]
	then
		if  [ $arg2 = Apache ]
	     	then
			echo " Apache "
			exit 
		elif[ $arg2 = MySQL ]
		then 
			echo " MySQL "
			exit
		else 	echo " Error " 
			exit
		fi 
	else 
		fi 
done 
	
