#!bin/bash

	read -p " Username;" user
	read -s -p " Password;" password
	if [ $user = admin ]
		then 
			if [ $(echo -n $password | openssl dgst -md5 | awk '{print $2}') = "21232f297a57a5a743894a0e4a801fc3" ]
				then 
					echo " Logged In , Welcome $user "
				else 
					echo " Invalid credentials!"
					exit

			fi 
		else 
			echo " Invalid crendentials!"
			exit
	fi
	
